// Mock data for destinations, packages, tips, and itineraries

export const destinations = [
  {
    id: 1,
    name: 'Lisbon, Portugal',
    location: 'Portugal',
    description: 'Historic streets, seaside vibes, and pastel tiles — a compact city for wandering.',
    duration: '3-5 days',
    price: 'INR 15,000',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    activities: ['Belém & Pastéis tasting', 'Alfama & Fado evening', 'Sintra day trip'],
  },
  {
    id: 2,
    name: 'Kyoto, Japan',
    location: 'Japan',
    description: 'Temples, gardens and centuries of culture. Perfect for mindful travel.',
    duration: '4-7 days',
    price: 'INR 45,000',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    activities: ['Temple visits', 'Garden tours', 'Traditional tea ceremony'],
  },
  {
    id: 3,
    name: 'Reykjavík, Iceland',
    location: 'Iceland',
    description: 'Otherworldly landscapes, geothermal pools and dramatic coasts.',
    duration: '5-8 days',
    price: 'INR 70,000',
    image: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80',
    activities: ['Northern Lights tour', 'Blue Lagoon', 'Golden Circle'],
  },
  {
    id: 4,
    name: 'Santorini, Greece',
    location: 'Greece',
    description: 'Stunning sunsets, white-washed buildings, and crystal-clear waters.',
    duration: '4-6 days',
    price: 'INR 35,000',
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80',
    activities: ['Sunset viewing', 'Wine tasting', 'Beach hopping'],
  },
  {
    id: 5,
    name: 'Bali, Indonesia',
    location: 'Indonesia',
    description: 'Tropical paradise with rich culture, stunning rice terraces, and pristine beaches.',
    duration: '5-7 days',
    price: 'INR 25,000',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    activities: ['Temple tours', 'Rice terrace trekking', 'Beach relaxation'],
  },
  {
    id: 6,
    name: 'Paris, France',
    location: 'France',
    description: 'The City of Light with iconic landmarks, world-class cuisine, and art.',
    duration: '4-6 days',
    price: 'INR 40,000',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    activities: ['Eiffel Tower', 'Louvre Museum', 'Seine cruise'],
  },
]

export const packages = [
  {
    id: 1,
    name: 'Budget Explorer',
    tier: 'budget',
    description: 'Perfect for travelers who want to explore without breaking the bank.',
    price: 15000,
    duration: '3-5 days',
    destination: 'Lisbon',
    features: [
      '3-star accommodation',
      'Breakfast included',
      'City tour',
      'Public transport pass',
      'Travel guide',
    ],
  },
  {
    id: 2,
    name: 'Standard Adventure',
    tier: 'standard',
    description: 'A balanced mix of comfort and adventure for the modern traveler.',
    price: 35000,
    duration: '4-6 days',
    destination: 'Santorini',
    features: [
      '4-star accommodation',
      'Breakfast & dinner',
      'Private tours',
      'Airport transfers',
      'Travel insurance',
      '24/7 support',
    ],
  },
  {
    id: 3,
    name: 'Premium Experience',
    tier: 'premium',
    description: 'Luxury travel with exclusive experiences and premium accommodations.',
    price: 70000,
    duration: '5-8 days',
    destination: 'Iceland',
    features: [
      '5-star accommodation',
      'All meals included',
      'Private guide',
      'Luxury transfers',
      'Exclusive experiences',
      'Spa treatments',
      'Concierge service',
    ],
  },
  {
    id: 4,
    name: 'Budget Explorer',
    tier: 'budget',
    description: 'Affordable way to experience the beauty of Bali.',
    price: 25000,
    duration: '5-7 days',
    destination: 'Bali',
    features: [
      '3-star accommodation',
      'Breakfast included',
      'Temple tours',
      'Transportation',
      'Travel guide',
    ],
  },
  {
    id: 5,
    name: 'Standard Adventure',
    tier: 'standard',
    description: 'Discover the charm of Paris with comfort and style.',
    price: 40000,
    duration: '4-6 days',
    destination: 'Paris',
    features: [
      '4-star accommodation',
      'Breakfast included',
      'Museum passes',
      'City tours',
      'Travel insurance',
      'Support',
    ],
  },
  {
    id: 6,
    name: 'Premium Experience',
    tier: 'premium',
    description: 'Immerse yourself in Japanese culture with luxury touches.',
    price: 45000,
    duration: '4-7 days',
    destination: 'Kyoto',
    features: [
      '5-star ryokan',
      'Traditional meals',
      'Private guide',
      'Cultural experiences',
      'Luxury transfers',
      'Concierge service',
    ],
  },
]

export const travelTips = [
  {
    id: 1,
    title: 'Pack Smart',
    category: 'Planning',
    content: 'Layering wins — check weather, bring a compact rain jacket and a daypack. Pack versatile clothing that can be mixed and matched, and always leave room for souvenirs.',
    readTime: 3,
  },
  {
    id: 2,
    title: 'Stay Local',
    category: 'Dining',
    content: 'Try neighborhood eateries — they often make the trip memorable. Avoid tourist traps and ask locals for recommendations. Street food can be some of the best food you\'ll have.',
    readTime: 4,
  },
  {
    id: 3,
    title: 'Flexible Plans',
    category: 'Planning',
    content: 'Leave pockets of free time; the best moments are often unplanned. While it\'s good to have an itinerary, allow yourself to wander and discover hidden gems.',
    readTime: 2,
  },
  {
    id: 4,
    title: 'Travel Insurance',
    category: 'Safety',
    content: 'Always invest in comprehensive travel insurance. It covers medical emergencies, trip cancellations, and lost luggage. Peace of mind is worth the cost.',
    readTime: 3,
  },
  {
    id: 5,
    title: 'Learn Basic Phrases',
    category: 'Culture',
    content: 'Learning a few key phrases in the local language shows respect and can enhance your experience. Start with greetings, please, thank you, and excuse me.',
    readTime: 2,
  },
  {
    id: 6,
    title: 'Document Everything',
    category: 'Planning',
    content: 'Keep digital copies of important documents (passport, visas, insurance) in cloud storage. Also carry physical copies in a separate location from originals.',
    readTime: 2,
  },
  {
    id: 7,
    title: 'Respect Local Customs',
    category: 'Culture',
    content: 'Research local customs and dress codes before you travel. What\'s acceptable at home might not be appropriate elsewhere. Respect goes a long way.',
    readTime: 3,
  },
  {
    id: 8,
    title: 'Stay Connected',
    category: 'Technology',
    content: 'Download offline maps, translation apps, and important travel apps before you leave. Consider getting a local SIM card or international data plan.',
    readTime: 2,
  },
]

export const sampleItineraries = {
  lisbon: {
    id: 'lisbon-4-days',
    destination: 'Lisbon, Portugal',
    duration: '4 days',
    days: [
      {
        title: 'Day 1 — Lisbon',
        description: 'Start slow: local markets then riverside sunset.',
        timeRange: '09:00 → 20:00',
        activities: [
          {
            time: '09:00',
            title: 'Breakfast at Mercado da Ribeira',
            description: 'Start your day with local pastries and coffee',
            location: 'Mercado da Ribeira',
          },
          {
            time: '11:00',
            title: 'Jerónimos Monastery',
            description: 'Explore this stunning UNESCO World Heritage site',
            location: 'Belém',
          },
          {
            time: '17:30',
            title: 'Sunset at Miradouro',
            description: 'Watch the sunset over the Tagus River',
            location: 'Alfama',
          },
        ],
      },
      {
        title: 'Day 2 — Sintra',
        description: 'Palaces and coastal viewpoints.',
        timeRange: '08:00 → 18:00',
        activities: [
          {
            time: '09:30',
            title: 'Pena Palace',
            description: 'Visit the colorful Romanticist palace',
            location: 'Sintra',
          },
          {
            time: '13:00',
            title: 'Lunch in Sintra town',
            description: 'Enjoy traditional Portuguese cuisine',
            location: 'Sintra',
          },
          {
            time: '16:00',
            title: 'Cabo da Roca (coast)',
            description: 'Visit the westernmost point of continental Europe',
            location: 'Cabo da Roca',
          },
        ],
      },
      {
        title: 'Day 3 — Alfama & Fado',
        description: 'Historic neighborhoods and evening music.',
        timeRange: '10:00 → 22:00',
        activities: [
          {
            time: '10:00',
            title: 'Alfama District Walk',
            description: 'Explore the oldest neighborhood in Lisbon',
            location: 'Alfama',
          },
          {
            time: '14:00',
            title: 'Castelo de São Jorge',
            description: 'Medieval castle with panoramic city views',
            location: 'Alfama',
          },
          {
            time: '20:00',
            title: 'Fado Evening',
            description: 'Experience traditional Portuguese music',
            location: 'Alfama',
          },
        ],
      },
    ],
  },
}

